# .github/workflows/main.yml
name: DataOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push data_processing image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/data_processing -f Dockerfile.data_processing .
        docker push ${{ secrets.DOCKER_USERNAME }}/data_processing

    - name: Build and push dashboard image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dashboard -f Dockerfile.dashboard .
        docker push ${{ secrets.DOCKER_USERNAME }}/dashboard

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.21.0

    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/data-processing-deployment.yaml
        kubectl apply -f k8s/dashboard-deployment.yaml
        kubectl apply -f k8s/dashboard-service.yaml
